### ISSUE TITLE
cnn

### ISSUE THREAD

**Issue by jschatz1** [LinusU/domain-name-regex#3]
This regex returns true for the string `cnn`

Is it correct that you aren't testing for the tld ?

**Comment by LinusU** [comment]
Are you sure about that? 🤔 

<img width="582" alt="Screenshot 2020-03-30 at 10 46 21" src="https://user-images.githubusercontent.com/189580/77898841-b44d6d00-7273-11ea-8497-cdb26eda4832.png">

**Comment by jschatz1** [comment]
I am sorry. I double checked before submitting. I must've made an error. I'll figure that out and post again.
